# Generated by Django 5.0.4 on 2024-05-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0002_alter_product_photo_or_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo_or_video',
        ),
        migrations.AddField(
            model_name='product',
            name='photos_or_videos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
