# Generated by Django 5.0.4 on 2024-05-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0005_productmedia_is_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='savatcha',
            name='product_amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='photos_or_videos',
            field=models.ManyToManyField(to='body.productmedia'),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='product_amount',
            field=models.IntegerField(),
        ),
    ]
