# Generated by Django 5.0.4 on 2024-05-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0007_liked_liked_liked_unique_liked_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liked',
            old_name='liked',
            new_name='liked_status',
        ),
    ]
