# Generated by Django 5.0.4 on 2024-07-26 15:00

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0008_rename_liked_liked_liked_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version_new', models.CharField(max_length=255)),
                ('version_last', models.CharField(default=' ', max_length=255, null=True)),
                ('link_for_IOS', models.CharField(max_length=255, null=True)),
                ('link_for_android', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='liked',
            name='unique_liked_product',
        ),
        migrations.RemoveField(
            model_name='liked',
            name='liked_status',
        ),
        migrations.AddField(
            model_name='liked',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e4578166-9c61-4fa9-aed3-57ca1ac28eca'), editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ex_owner_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ex_owner_tg_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='savatcha',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ce53f886-3dc3-47c6-a429-7d03797875b3'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='liked',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='savatcha',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='liked',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='liked_product'),
        ),
    ]
