# Generated by Django 5.1.1 on 2024-10-03 17:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0009_versions_remove_liked_unique_liked_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('883fbdc3-3164-4e08-82ec-4c8050ea86d5'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='savatcha',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3f93cbac-e616-4149-88d3-ad3d8ac43c4d'), editable=False, unique=True),
        ),
    ]
