# Generated by Django 5.1.1 on 2024-10-03 17:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0011_alter_liked_uuid_alter_savatcha_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('df399a96-84e2-4160-a6d5-e1381b1a17d0'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='savatcha',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8896e0ee-cb1e-44a4-8689-9d45458aac1e'), editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='body.subcategory'),
        ),
    ]
