# Generated by Django 5.1.1 on 2024-10-03 17:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0012_alter_liked_uuid_alter_savatcha_uuid_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1ad0a8cb-eddf-4936-8f15-4e907ca46390'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='savatcha',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ef068ec6-92da-4bde-b0d9-77a1703c171e'), editable=False, unique=True),
        ),
    ]
