# Generated by Django 5.1.1 on 2024-10-03 17:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0013_alter_liked_uuid_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('55dce280-5cec-403e-9065-3d2dee06c67a'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='savatcha',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8e1bdcc9-2f72-464c-b3d6-e849bd8f41f1'), editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='ProductMediaRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.product')),
                ('productmedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.productmedia')),
            ],
            options={
                'unique_together': {('product', 'productmedia')},
            },
        ),
    ]
